### ISSUE TITLE
Broken links on blog post

### ISSUE THREAD

**Issue by tayloramurphy** [fishtown-analytics/snowplow-bigquery#2]
It looks like [this commit](https://github.com/fishtown-analytics/snowplow-bigquery/commit/d103afd5348fdeb30af3032da5819ddb3a6b9dc1) broke at least two of the links on the "What, exactly, is dbt?" [blog post](https://blog.fishtownanalytics.com/what-exactly-is-dbt-47ba57309068)

Just FYI.

**Comment by drewbanin** [comment]
thanks @tayloramurphy!

**Comment by jthandy** [comment]
Thanks for the heads up! I just fixed both links. I should be more careful in the future :D
